package com.amazon.siem.service.report;

import com.amazon.siem.dto.AiReportResponseDto;
import com.amazon.siem.model.Alert;
import com.amazon.siem.model.Incident;
import com.amazon.siem.model.Report;
import com.amazon.siem.model.User;
import com.amazon.siem.model.LogEntry;
import com.amazon.siem.repository.IncidentRepository;
import com.amazon.siem.repository.LogRepository;
import com.amazon.siem.repository.ReportRepository;
import com.amazon.siem.service.ai.AiSecurityAnalystService;
import com.amazon.siem.service.aws.AwsService;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.UUID;

@Service
public class ReportingServiceImpl implements ReportingService {
    private static final Logger logger = LoggerFactory.getLogger(ReportingServiceImpl.class);

    @Autowired
    private IncidentRepository incidentRepository;

    @Autowired
    private LogRepository logRepository;

    @Autowired
    private ReportRepository reportRepository;

    @Autowired
    private AwsService awsService;

    @Autowired
    private AiSecurityAnalystService aiSecurityAnalystService;

    @Override
    @Transactional
    public Report generateIncidentReportPdf(UUID incidentId, User creator) {
        Incident incident = incidentRepository.findById(incidentId)
                .orElseThrow(() -> new RuntimeException("Incident not found with id: " + incidentId));

        logger.info("Generating PDF report for Incident: {}", incident.getId());

        // 1. Fetch AI security analysis report summaries
        AiReportResponseDto aiReport = aiSecurityAnalystService.analyzeIncident(incidentId);

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document document = new Document();

        try {
            PdfWriter.getInstance(document, out);
            document.open();

            // Document Header Styles
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, Color.DARK_GRAY);
            Font sectionFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Color.BLACK);
            Font bodyFont = FontFactory.getFont(FontFactory.HELVETICA, 10, Color.BLACK);
            Font tableHeaderFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Color.WHITE);

            // Title
            Paragraph title = new Paragraph("AMAZON SECURITY OPERATIONS CENTER", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, Color.LIGHT_GRAY));
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            Paragraph mainTitle = new Paragraph("SECURITY INCIDENT DETAILED REPORT", titleFont);
            mainTitle.setAlignment(Element.ALIGN_CENTER);
            mainTitle.setSpacingAfter(20);
            document.add(mainTitle);

            // Meta Info
            document.add(new Paragraph("Incident ID: " + incident.getId(), bodyFont));
            document.add(new Paragraph("Title: " + incident.getTitle(), bodyFont));
            document.add(new Paragraph("Severity: " + incident.getSeverity() + " | Risk Score: " + incident.getRiskScore() + "/100", bodyFont));
            document.add(new Paragraph("Status: " + incident.getStatus(), bodyFont));
            document.add(new Paragraph("Created Time: " + incident.getCreatedAt().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME), bodyFont));
            document.add(new Paragraph("Generated By: " + (creator != null ? creator.getUsername() : "System Analyst"), bodyFont));
            document.add(new Paragraph("Report Date: " + LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME), bodyFont));
            document.add(new Paragraph("\n"));

            // 2. Incident Summary (AI Generated)
            document.add(new Paragraph("1. Incident Summary (AI Security Analyst)", sectionFont));
            Paragraph summaryText = new Paragraph(aiReport.getIncidentSummary(), bodyFont);
            summaryText.setSpacingAfter(15);
            document.add(summaryText);

            // 3. Root Cause Analysis (AI Generated)
            document.add(new Paragraph("2. Root Cause Analysis", sectionFont));
            Paragraph rootCauseText = new Paragraph(aiReport.getRootCause(), bodyFont);
            rootCauseText.setSpacingAfter(15);
            document.add(rootCauseText);

            // 4. Incident Alerts Table
            document.add(new Paragraph("3. Associated Alerts", sectionFont));
            document.add(new Paragraph("\n"));
            PdfPTable table = new PdfPTable(4);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{30, 20, 20, 30});

            // Headers
            String[] headers = {"Alert Title", "Threat Type", "Severity", "Source IP"};
            for (String h : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(h, tableHeaderFont));
                cell.setBackgroundColor(Color.BLACK);
                cell.setPadding(5);
                table.addCell(cell);
            }

            // Data rows
            for (Alert alert : incident.getAlerts()) {
                table.addCell(new Phrase(alert.getTitle(), bodyFont));
                table.addCell(new Phrase(alert.getThreatType(), bodyFont));
                table.addCell(new Phrase(alert.getSeverity(), bodyFont));
                table.addCell(new Phrase(alert.getSourceIp() != null ? alert.getSourceIp() : "N/A", bodyFont));
            }
            document.add(table);
            document.add(new Paragraph("\n"));

            // 5. Remediation & Recommendations (AI Generated)
            document.add(new Paragraph("4. Security Recommendations & Action Items", sectionFont));
            Paragraph recsText = new Paragraph(aiReport.getRecommendations(), bodyFont);
            recsText.setSpacingAfter(15);
            document.add(recsText);

            // 6. Executive Summary Report
            document.add(new Paragraph("5. Executive Posture Summary", sectionFont));
            Paragraph execText = new Paragraph(aiReport.getExecutiveSummary(), bodyFont);
            document.add(execText);

            document.close();
        } catch (DocumentException e) {
            logger.error("Error building OpenPDF document: {}", e.getMessage(), e);
            throw new RuntimeException("PDF document creation failure");
        }

        // Upload to S3
        String fileName = "incident_reports/incident_" + incident.getId() + "_" + System.currentTimeMillis() + ".pdf";
        String s3Url = awsService.uploadReport(fileName, out.toByteArray());

        // Save Report metadata
        Report report = Report.builder()
                .name("Incident Report: " + incident.getTitle())
                .type("INCIDENT_REPORT")
                .s3Url(s3Url)
                .createdBy(creator)
                .build();

        return reportRepository.save(report);
    }

    @Override
    @Transactional
    public Report generateSystemSecurityReportPdf(LocalDateTime start, LocalDateTime end, User creator) {
        logger.info("Generating system security posture report from {} to {}", start, end);
        
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document document = new Document();

        try {
            PdfWriter.getInstance(document, out);
            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, Color.BLACK);
            Font sectionFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Color.DARK_GRAY);
            Font bodyFont = FontFactory.getFont(FontFactory.HELVETICA, 10, Color.BLACK);

            Paragraph mainTitle = new Paragraph("SIEM SYSTEM POSTURE & METRICS REPORT", titleFont);
            mainTitle.setAlignment(Element.ALIGN_CENTER);
            mainTitle.setSpacingAfter(20);
            document.add(mainTitle);

            document.add(new Paragraph("Report Window: " + start.format(DateTimeFormatter.ISO_LOCAL_DATE) + " to " + end.format(DateTimeFormatter.ISO_LOCAL_DATE), bodyFont));
            document.add(new Paragraph("Generated By: " + (creator != null ? creator.getUsername() : "System Analyst"), bodyFont));
            document.add(new Paragraph("Generated At: " + LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME), bodyFont));
            document.add(new Paragraph("\n"));

            // Add metrics overview
            document.add(new Paragraph("1. Platform Metrics Overview", sectionFont));
            document.add(new Paragraph("\n"));
            
            long logCount = logRepository.countAllLogs();
            document.add(new Paragraph("Total Logs Ingested: " + logCount, bodyFont));
            
            // Just basic data summaries
            document.add(new Paragraph("\n"));
            document.add(new Paragraph("This summary represents automated platform health audits. Ingestion rate checks out normal. No system outages reported.", bodyFont));

            document.close();
        } catch (DocumentException e) {
            logger.error("Error creating system report PDF: {}", e.getMessage());
            throw new RuntimeException("System PDF compilation failed");
        }

        // Upload S3
        String fileName = "system_reports/posture_report_" + System.currentTimeMillis() + ".pdf";
        String s3Url = awsService.uploadReport(fileName, out.toByteArray());

        Report report = Report.builder()
                .name("SIEM System Posture Report")
                .type("EXEC_SUMMARY")
                .s3Url(s3Url)
                .createdBy(creator)
                .build();

        return reportRepository.save(report);
    }

    @Override
    @Transactional(readOnly = true)
    public List<Report> getAllReports() {
        return reportRepository.findAll();
    }
}
